### ISSUE TITLE
missing options 

### ISSUE THREAD

**Issue by Xgamefactory** [testfairy/node-testfairy-uploader#1]
Hi,
How to enable _Collect logs when app in background_ and _Require login before download_
using upload api ?

**Comment by yairba** [comment]
It is not possible to do that with the API.
Please enable these settings on the web interface.

**Comment by Xgamefactory** [comment]
these options are important 
Developers uses Upload api to automate this task 
without all these dev options this upload api looks incomplete.

**Comment by yairba** [comment]
Let's take this discussion offline, can you please email us to support at testfairy dot com?

**Comment by Xgamefactory** [comment]
We did send via Support form on dashboard.

**Comment by yairba** [comment]
Can you please send again?

**Comment by Xgamefactory** [comment]
We resend it to support at testfairy dot com
